# Generated by Django 3.1 on 2020-08-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='displayname',
        ),
    ]
