# Generated by Django 3.1 on 2020-09-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20200831_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='followers',
        ),
    ]
